<a href="https://colab.research.google.com/github/riqleonarvenLL/LEAL-2ECEC-PA1/blob/main/LEALECE2112PA2_pynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
#set random seed (so results are the same every run)
np.random.seed(1234)

In [7]:
#make a random 5x5 matrix with values between 10 and 100
X = np.random.randint(1, 51, (4, 4))

In [8]:
#normalize the matrix (subtract mean, divide by std)
X_normalized = (X - X.mean()) / X.std()

In [9]:
print("Matrix X:")
print(X)

print("\nNormalized X:")
print(X_normalized)

print("\nMean of normalized X:", X_normalized.mean())
print("STD of normalized X:", X_normalized.std())

Matrix X:
[[48 20 39 13]
 [25 16 50 24]
 [42 27 31 44]
 [31 45 27 49]]

Normalized X:
[[ 1.25344202 -1.11593361  0.49185699 -1.70827752]
 [-0.69283082 -1.45441584  1.42268313 -0.77745138]
 [ 0.74571867 -0.5235897  -0.18510747  0.91495979]
 [-0.18510747  0.99958034 -0.5235897   1.33806258]]

Mean of normalized X: -6.938893903907228e-18
STD of normalized X: 1.0


B. Cubes Divisible by 4


In [ ]:
import numpy as np

In [ ]:
nums = np.arange(1, 101)

In [ ]:
cubes = nums ** 3

In [ ]:
C = cubes.reshape(10, 10)

In [ ]:
div_by_4 = C[C % 4 == 0]

In [ ]:
print("Shape of C:", C.shape)

Shape of C: (10, 10)


In [ ]:
print("\nCubes divisible by 4:")
print(div_by_4)


Cubes divisible by 4:
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]


In [ ]:
print("\nNumber of selected elements:", div_by_4.size)


Number of selected elements: 50


In [ ]:
np.save("div_by_4.npy", div_by_4)

C. Above Mean Sqaures Problem

In [10]:
import numpy as np

In [13]:
nums = np.arange(1, 37)

In [14]:
squares = nums ** 2

In [15]:
S = squares.reshape(6, 6)

In [16]:
S_mean = S.mean()

In [17]:
above_mean = S[S > S_mean]

In [18]:
print("Array S:")
print(S)

Array S:
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]


In [19]:
print("\nMean of S:", S_mean)


Mean of S: 450.1666666666667


In [20]:
print("\nValues above the mean:")
print(above_mean)


Values above the mean:
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]


In [21]:
print("\nNumber of selected elements:", above_mean.size)


Number of selected elements: 15


In [22]:
np.save("above_mean.npy", above_mean)